### ISSUE TITLE
Getting the location / media id after downloading?

### ISSUE THREAD

**Issue by fransyozef** [Nomia/ImgDownloader#2]
Hi
I'm using ionic and used your plugin. It works perfectly (in my simulator). It downloads a image from a remote server and puts it in my camera roll. 

Is there a way to get a reference back to the downloaded file, for example the filename / media id?

**Comment by Nomia** [comment]
try this:

```
onDeviceReady = function(){
    cordova.plugins.imgDownloader.download("/myImages/logo.png",function(path){
        alert(path);
    },function(){
        alert("error");
    });        
}
```
